"""add reserved_by_id to wish

Revision ID: 50a8066b25df
Revises: 290908583dd4
Create Date: 2025-12-11 17:34:03.427545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Add this line


# revision identifiers, used by Alembic.
revision: str = '50a8066b25df'
down_revision: Union[str, Sequence[str], None] = '290908583dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
