#!/usr/bin/env bash
# Generate static/css/tailwind.css with the Tailwind v3 standalone executable.
# No Node.js / npm required: this is a download-once local binary.
set -euo pipefail

VERSION="v3.4.17"
ASSET="tailwindcss-macos-arm64"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${REPO_ROOT}/tools/.bin"
BIN="${BIN_DIR}/tailwindcss-${VERSION}"
INPUT="${REPO_ROOT}/static/css/tailwind.src.css"
OUTPUT="${REPO_ROOT}/static/css/tailwind.css"
CONFIG="${REPO_ROOT}/tailwind.config.js"
BANNER="/* Generated by tools/build_tailwind.sh - do not edit. Source: tailwind.config.js + templates/ + main.py. */"

mkdir -p "${BIN_DIR}"
if [ ! -x "${BIN}" ]; then
  echo "Downloading Tailwind ${VERSION} standalone (${ASSET})..."
  curl -fsSL -o "${BIN}" \
    "https://github.com/tailwindlabs/tailwindcss/releases/download/${VERSION}/${ASSET}"
  chmod +x "${BIN}"
fi

"${BIN}" -c "${CONFIG}" -i "${INPUT}" -o "${OUTPUT}" --minify
printf '%s\n' "${BANNER}" | cat - "${OUTPUT}" > "${OUTPUT}.tmp" && mv "${OUTPUT}.tmp" "${OUTPUT}"
echo "Wrote ${OUTPUT}"
