#!/usr/bin/env python3
"""Generate local Phosphor SVG icons and their CSS from pinned upstream assets.

Replaces the @phosphor-icons/web web fonts (previously loaded from cdn.jsdelivr.net
in templates/base.html) with per-icon local SVGs rendered through CSS mask-image.

Pipeline:
  1. Scan templates/**/*.html + main.py for `class="..."` attributes and collect
     the used (weight, name) pairs. Only class-attribute tokens are considered so
     the word "ph" inside unrelated words never matches.
  2. Download every non-duotone icon from the pinned @phosphor-icons/core release
     into static/icons/<weight>/<name>.svg (deterministic overwrite).
  3. Write static/css/phosphor.css: one shared base rule plus one mask-image rule
     per used icon, colored with `background-color: currentColor`.

Duotone icons are intentionally skipped here: their two-tone effect is inlined as
literal <svg> in the templates (see the work unit odd/tasks/phosphor-svg.md).

Stdlib only. Run from anywhere; paths are resolved relative to the repo root.
"""

from __future__ import annotations

import re
import ssl
import sys
import urllib.error
import urllib.request
from pathlib import Path

VERSION = "2.1.1"
BASE_URL = f"https://cdn.jsdelivr.net/npm/@phosphor-icons/core@{VERSION}/assets"
BANNER = (
    "/* Generated by tools/build_phosphor_icons.py - do not edit. "
    f"Source: @phosphor-icons/core@{VERSION} (cdn.jsdelivr.net). */"
)
BASE_RULE = (
    ".ph,.ph-bold,.ph-fill,.ph-duotone,.ph-light,.ph-thin{display:inline-block;"
    "width:1em;height:1em;vertical-align:-.125em;"
    "-webkit-mask-repeat:no-repeat;mask-repeat:no-repeat;"
    "-webkit-mask-position:center;mask-position:center;"
    "-webkit-mask-size:100% 100%;mask-size:100% 100%}"
)

ROOT = Path(__file__).resolve().parents[1]
ICONS_DIR = ROOT / "static" / "icons"
CSS_PATH = ROOT / "static" / "css" / "phosphor.css"

# Weight token -> canonical weight directory. Bare `ph` is the regular weight.
WEIGHT_TOKENS = {
    "ph": "regular",
    "ph-bold": "bold",
    "ph-fill": "fill",
    "ph-duotone": "duotone",
    "ph-light": "light",
    "ph-thin": "thin",
}
WEIGHT_ORDER = ("regular", "bold", "fill")

_CLASS_ATTR = re.compile(r"""class\s*=\s*(?:"([^"]*)"|'([^']*)')""")
_ICON_TOKEN = re.compile(r"ph-[a-z0-9-]+")


def _sources() -> list[Path]:
    templates = sorted((ROOT / "templates").rglob("*.html"))
    main_py = ROOT / "main.py"
    return templates + [main_py]


def scan_used_icons() -> set[tuple[str, str]]:
    """Return the used non-duotone (weight, name) pairs from the sources.

    Every `class="..."` attribute is tokenized by whitespace; the weight token(s)
    and the `ph-<name>` token(s) of the same attribute are paired together.
    """
    used: set[tuple[str, str]] = set()
    for source in _sources():
        text = source.read_text(encoding="utf-8")
        for match in _CLASS_ATTR.finditer(text):
            value = match.group(1) if match.group(1) is not None else match.group(2)
            tokens = value.split()
            weights = [WEIGHT_TOKENS[t] for t in tokens if t in WEIGHT_TOKENS]
            names = [
                t for t in tokens
                if t not in WEIGHT_TOKENS and _ICON_TOKEN.fullmatch(t)
            ]
            for name in names:
                for weight in weights:
                    if weight == "duotone":
                        continue
                    used.add((weight, name.removeprefix("ph-")))
    return used


def _ssl_context() -> ssl.SSLContext:
    """CA bundle that works on this macOS Python while keeping verification on."""
    for cafile in ("/etc/ssl/cert.pem", "/private/etc/ssl/cert.pem"):
        if Path(cafile).is_file():
            return ssl.create_default_context(cafile=cafile)
    return ssl.create_default_context()


def remote_url(weight: str, name: str) -> str:
    if weight == "regular":
        return f"{BASE_URL}/regular/{name}.svg"
    return f"{BASE_URL}/{weight}/{name}-{weight}.svg"


def download(context: ssl.SSLContext, weight: str, name: str, target: Path) -> int:
    url = remote_url(weight, name)
    try:
        with urllib.request.urlopen(url, timeout=30, context=context) as response:
            body = response.read()
    except (urllib.error.URLError, urllib.error.HTTPError, OSError) as exc:
        raise SystemExit(f"ERROR: failed to download {url}: {exc}") from exc
    if b"<svg" not in body:
        raise SystemExit(f"ERROR: {url} did not return an SVG (got {body[:40]!r})")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(body)
    return len(body)


def selector_for(weight: str, name: str) -> str:
    if weight == "regular":
        return f".ph.ph-{name}"
    return f".ph-{weight}.ph-{name}"


def rule_for(weight: str, name: str) -> str:
    url = f"/static/icons/{weight}/{name}.svg"
    return (
        f"{selector_for(weight, name)}"
        f'{{background-color:currentColor;'
        f'-webkit-mask-image:url("{url}");mask-image:url("{url}")}}'
    )


def write_css(used: set[tuple[str, str]]) -> None:
    ordered = sorted(used, key=lambda pair: (WEIGHT_ORDER.index(pair[0])
                                             if pair[0] in WEIGHT_ORDER else 99, pair[1]))
    lines = [BANNER, BASE_RULE] + [rule_for(w, n) for w, n in ordered]
    CSS_PATH.parent.mkdir(parents=True, exist_ok=True)
    CSS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    used = scan_used_icons()
    if not used:
        raise SystemExit("ERROR: no Phosphor icon usages found; scan broken?")
    context = _ssl_context()
    total_bytes = 0
    for weight, name in sorted(used):
        target = ICONS_DIR / weight / f"{name}.svg"
        total_bytes += download(context, weight, name, target)
    write_css(used)
    print(f"Downloaded {len(used)} icons ({total_bytes} bytes) into {ICONS_DIR}")
    print(f"Wrote {CSS_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
