#!/usr/bin/env bash
# Generate static/css/tailwind.css with the Tailwind v4 standalone executable.
# No Node.js / npm required: this is a download-once local binary.
#
# Integrity model: the executable is downloaded over HTTPS from the official
# GitHub release and verified against a pinned SHA-256 before it is ever run.
# The v4.3.3 release publishes no signed checksum, so these hashes are TOFU
# (trust-on-first-use) values captured from the official HTTPS downloads.
set -euo pipefail

VERSION="v4.3.3"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${REPO_ROOT}/tools/.bin"

# Resolve the target asset: explicit override wins, otherwise detect the platform.
if [ -n "${TAILWIND_ASSET:-}" ]; then
  ASSET="${TAILWIND_ASSET}"
else
  case "$(uname -s)/$(uname -m)" in
    Darwin/arm64)  ASSET="tailwindcss-macos-arm64" ;;
    Darwin/x86_64) ASSET="tailwindcss-macos-x64" ;;
    Linux/x86_64)  ASSET="tailwindcss-linux-x64" ;;
    *)
      echo "ERROR: unsupported platform '$(uname -s)/$(uname -m)'." >&2
      echo "Set TAILWIND_ASSET to a tailwindcss release asset and TAILWIND_SHA256" >&2
      echo "to its expected SHA-256, then re-run. Refusing to download unverified." >&2
      exit 1
      ;;
  esac
fi

# Resolve the expected hash: explicit override wins, otherwise the pinned map.
if [ -n "${TAILWIND_SHA256:-}" ]; then
  EXPECTED_SHA="${TAILWIND_SHA256}"
else
  case "${ASSET}" in
    tailwindcss-macos-arm64) EXPECTED_SHA="cdf646702987a743464dff4d9c60fd4480d1c1e73dd819a9a67f1078815dce9d" ;;
    tailwindcss-macos-x64)   EXPECTED_SHA="7922e0953f2110c05976e3bf58f14e643d90427575e766b7d433f5f80cbee7e1" ;;
    tailwindcss-linux-x64)   EXPECTED_SHA="dc61b3ac6b8c9ca874c0cc4c57b2409791a64c5540404ca5f5367360babc313a" ;;
    *)
      echo "ERROR: no pinned SHA-256 for asset '${ASSET}'." >&2
      echo "Set TAILWIND_SHA256 to the expected SHA-256, then re-run." >&2
      exit 1
      ;;
  esac
fi

URL="https://github.com/tailwindlabs/tailwindcss/releases/download/${VERSION}/${ASSET}"
# Cache path is keyed by both version and asset so platforms never collide.
BIN="${BIN_DIR}/tailwindcss-${VERSION}-${ASSET}"

hash_of() {
  shasum -a 256 "$1" | awk '{print $1}'
}

download() {
  echo "Downloading Tailwind ${VERSION} standalone (${ASSET})..."
  curl -fsSL --retry 3 --retry-delay 1 --connect-timeout 15 --max-time 300 \
    -o "${BIN}" "${URL}"
  actual="$(hash_of "${BIN}")"
  if [ "${actual}" != "${EXPECTED_SHA}" ]; then
    rm -f "${BIN}"
    echo "ERROR: SHA-256 mismatch for ${ASSET} (${URL})" >&2
    echo "  expected: ${EXPECTED_SHA}" >&2
    echo "  actual:   ${actual}" >&2
    exit 1
  fi
  chmod +x "${BIN}"
  echo "Verified SHA-256 ${actual}"
}

mkdir -p "${BIN_DIR}"
if [ -x "${BIN}" ]; then
  cached="$(hash_of "${BIN}")"
  if [ "${cached}" = "${EXPECTED_SHA}" ]; then
    echo "Using cached ${BIN} (SHA-256 verified)"
  else
    echo "Cached ${BIN} failed SHA-256 verification; re-downloading" >&2
    rm -f "${BIN}"
    download
  fi
else
  download
fi

# static/css/tailwind.src.css declares relative @source globs, so run from the repo root.
cd "${REPO_ROOT}"
BANNER="/* Generated by tools/build_tailwind.sh - do not edit. Source: static/css/tailwind.src.css + templates/ + main.py. */"

"${BIN}" -i static/css/tailwind.src.css -o static/css/tailwind.css --minify
printf '%s\n' "${BANNER}" | cat - static/css/tailwind.css > static/css/tailwind.css.tmp \
  && mv static/css/tailwind.css.tmp static/css/tailwind.css
echo "Wrote ${REPO_ROOT}/static/css/tailwind.css"
